
import React, { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ModernTiptapEditor } from '@/components/editor/ModernTiptapEditor';
import { useToast } from '@/hooks/use-toast';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const TinyMCEDemo: React.FC = () => {
  const [content, setContent] = useState('<p>Welcome to Tiptap Editor! Start editing this content or type "/" for commands...</p>');
  const [savedContent, setSavedContent] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [lastSaved, setLastSaved] = useState<Date | null>(null);
  const { toast } = useToast();

  const handleSave = useCallback(async () => {
    setIsSaving(true);
    try {
      // Simulate save operation
      await new Promise(resolve => setTimeout(resolve, 500));
      setSavedContent(content);
      setLastSaved(new Date());
      toast({
        title: "Content saved",
        description: "Your content has been saved successfully",
      });
    } catch (error) {
      toast({
        title: "Save failed",
        description: "Failed to save content. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSaving(false);
    }
  }, [content, toast]);

  const handleClear = () => {
    setContent('');
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow">
        <div className="container mx-auto px-4 py-8 max-w-6xl">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="space-y-8"
          >
            <div className="text-center">
              <h1 className="text-4xl font-bold text-gray-900 mb-4">
                Tiptap Editor Demo
              </h1>
              <p className="text-xl text-gray-600 max-w-3xl mx-auto">
                Experience the power of Tiptap rich text editor with modern toolbar and slash commands.
              </p>
            </div>

            <Card>
              <CardHeader>
                <CardTitle>Rich Text Editor</CardTitle>
                <CardDescription>
                  Use the editor below to create and format content with Tiptap's powerful features and toolbar.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <ModernTiptapEditor
                  content={content}
                  onChange={setContent}
                  onSave={handleSave}
                  placeholder="Start creating amazing content or type '/' for commands..."
                  className="min-h-[400px]"
                  autoSave={false}
                />
                
                <div className="flex items-center justify-between">
                  <div className="flex gap-2">
                    <Button onClick={handleSave} disabled={isSaving}>
                      {isSaving ? 'Saving...' : 'Save Content'}
                    </Button>
                    <Button variant="outline" onClick={handleClear}>
                      Clear Editor
                    </Button>
                  </div>
                  {lastSaved && (
                    <div className="text-sm text-muted-foreground">
                      Last saved: {lastSaved.toLocaleTimeString()}
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            {savedContent && (
              <Card>
                <CardHeader>
                  <CardTitle>Saved Content Preview</CardTitle>
                  <CardDescription>
                    This is how your saved content will appear when rendered.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div 
                    className="prose prose-lg max-w-none"
                    dangerouslySetInnerHTML={{ __html: savedContent }}
                  />
                </CardContent>
              </Card>
            )}

            <Card>
              <CardHeader>
                <CardTitle>Content Source (HTML)</CardTitle>
                <CardDescription>
                  View the raw HTML generated by the editor.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <pre className="bg-gray-100 p-4 rounded-lg overflow-x-auto text-sm">
                  <code>{content}</code>
                </pre>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Tiptap Editor Features</CardTitle>
                <CardDescription>
                  Key features available in this modern editor:
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm">
                  <li>• Modern floating toolbar</li>
                  <li>• Rich text formatting (bold, italic, etc.)</li>
                  <li>• Multiple heading levels</li>
                  <li>• Lists and bullet points</li>
                  <li>• Text alignment options</li>
                  <li>• Link insertion</li>
                  <li>• Image embedding</li>
                  <li>• Slash commands (/)</li>
                  <li>• Blockquotes and code blocks</li>
                  <li>• Undo/Redo functionality</li>
                  <li>• Text color with opacity</li>
                  <li>• Text highlighting</li>
                  <li>• Manual save functionality</li>
                  <li>• Responsive design</li>
                </ul>
              </CardContent>
            </Card>
          </motion.div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default TinyMCEDemo;
