-- Seed all SEO metadata for projects, blog posts, and static pages

-- Insert static pages
INSERT INTO public.seo_meta (slug, path_type, title, description, canonical_url, og_image_url, keywords) VALUES
('home', 'page', 'Hiram Barsky | Lead Product Designer & AI Innovator — Barsky Design', 'Driving Design Strategy & Leadership | Passion for High Craft, Gen AI, Cyber & Fintech | Based in Clifton, NJ', 'https://barskydesign.pro/', 'https://barskydesign.pro/images/hiram-barsky-headshot.jpg', ARRAY['UX Designer', 'Product Designer', 'AI Design', 'Clifton NJ']),
('projects', 'page', 'UX Case Studies & Product Design Portfolio — Barsky Design', 'Explore UX case studies in healthcare, fintech, co-parenting, and AI platforms — showcasing measurable impact, user outcomes, and strategic design thinking.', 'https://barskydesign.pro/projects', 'https://barskydesign.pro/images/herbalink-desktop-1.webp', ARRAY['UX Case Studies', 'Product Design Portfolio', 'Design Work']),
('about', 'page', 'About Hiram Barsky | 15+ Years Product Design Leadership — Barsky Design', 'Senior UX/Product Designer with 15+ years creating data-driven, AI-powered platforms. Based in Clifton, NJ, serving clients nationwide.', 'https://barskydesign.pro/about', 'https://barskydesign.pro/images/hiram-barsky-headshot.jpg', ARRAY['UX Designer Bio', 'Product Design Experience', 'Design Leadership']),
('services', 'page', 'Expert UX/UI Design Services | Mobile Apps & Web Development — Barsky Design', 'From user research to high-impact product design, I help teams turn complex ideas into simple, intuitive experiences that drive business results.', 'https://barskydesign.pro/services', 'https://barskydesign.pro/images/macbookpro.png', ARRAY['UX Design Services', 'Product Design', 'UI Design']),
('contact', 'page', 'Contact Barsky Design | Product Design & UX Consulting in NJ — Barsky Design', 'Ready to transform your product? Book a call to discuss your vision, UX challenges, or collaboration opportunities in Clifton, NJ and beyond.', 'https://barskydesign.pro/contact', 'https://barskydesign.pro/images/hiram-barsky-headshot.jpg', ARRAY['Contact Designer', 'UX Consultation', 'Design Services']),
('blog', 'page', 'UX Design Blog | Product Design Insights & Case Studies — Barsky Design', 'Expert insights on UX design, AI integration, design systems, and product strategy — practical lessons from 15+ years in the field.', 'https://barskydesign.pro/blog', 'https://barskydesign.pro/images/blog-ai-enhanced-ux.jpg', ARRAY['UX Blog', 'Design Insights', 'Product Strategy']),
('store', 'page', 'Design Resources & Templates | Premium UX Tools — Barsky Design', 'Professional design resources, wireframe kits, and UX templates to accelerate your product development. Digital downloads available instantly.', 'https://barskydesign.pro/store', 'https://barskydesign.pro/images/hiram-barsky-headshot.jpg', ARRAY['Design Resources', 'UX Templates', 'Wireframe Kits']),
('ux-ui-design', 'page', 'Expert UX/UI Design Services | User-Centered Product Design — Barsky Design', 'Transform your product with expert UX/UI design. From user research to high-fidelity prototypes, I create intuitive experiences that drive results.', 'https://barskydesign.pro/design-services/ux-ui-design', 'https://barskydesign.pro/images/ux-ui-design-service.jpg', ARRAY['UX Design', 'UI Design', 'User Research']),
('mobile-app-design', 'page', 'Mobile App Design Services | iOS & Android UX/UI — Barsky Design', 'Native and cross-platform mobile app design for iOS and Android. User-centered design that increases engagement and app store ratings.', 'https://barskydesign.pro/design-services/mobile-app-design', 'https://barskydesign.pro/images/mobile-app-design-service.jpg', ARRAY['Mobile App Design', 'iOS Design', 'Android Design']),
('web-development', 'page', 'Modern Web Development | React & Frontend Development — Barsky Design', 'Custom web development with React, TypeScript, and modern frameworks. Fast, responsive, and accessible web applications that scale.', 'https://barskydesign.pro/design-services/web-development', 'https://barskydesign.pro/images/web-development-service.jpg', ARRAY['Web Development', 'React Development', 'Frontend Development'])
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  canonical_url = EXCLUDED.canonical_url,
  og_image_url = EXCLUDED.og_image_url,
  keywords = EXCLUDED.keywords,
  updated_at = now();

-- Insert all 8 projects
INSERT INTO public.seo_meta (slug, path_type, title, description, canonical_url, og_image_url, keywords) VALUES
('smarterhealth', 'project', 'Smarter Health – Helping Patients Stay on Track | Hiram Barsky', 'Healthcare app that increased medication adherence by 45% and appointment booking by 60% through empathy-driven UX and simplified onboarding.', 'https://barskydesign.pro/project/smarterhealth', 'https://ctqttomppgkjbjkckise.supabase.co/storage/v1/object/public/published-images/smarterhealth/frontpage.png', ARRAY['Healthcare App', 'Mobile App Design', 'UX Design', 'Accessibility', 'Patient Engagement']),
('crypto', 'project', 'Crypto Trading Platform UX | Fintech Case Study — Barsky Design', 'Fintech trading platform that reduced onboarding drop-off by 35% and order errors by 45% through dual-mode interface design for beginners and pros.', 'https://barskydesign.pro/project/crypto', 'https://ctqttomppgkjbjkckise.supabase.co/storage/v1/object/public/published-images/crypto/dashboardmobileanddesktopcrypto.jpg', ARRAY['Crypto Design', 'Fintech UX', 'Trading Platform', 'Dual-Mode Interface', 'Financial Technology']),
('daesearchproject', 'project', 'Enterprise Data Discovery | Search UX Case Study — Barsky Design', 'Advanced search platform with faceted filters and relevance tuning that helps data analysts find trustworthy assets 3x faster across enterprise sources.', 'https://barskydesign.pro/project/daesearchproject', 'https://barskydesign.pro/images/dae-search-desktop-1.webp', ARRAY['Enterprise Search', 'Data Discovery', 'UX Design', 'B2B Software', 'Information Architecture']),
('investor-loan-app', 'project', 'Fintech Loan Platform | Investment App UX Case Study — Barsky Design', 'Streamlined fintech underwriting that cut loan processing time 40% while improving compliance, decision clarity, and borrower experience through better UX.', 'https://barskydesign.pro/project/investor-loan-app', 'https://barskydesign.pro/images/investor-loan-app-desktop-1.webp', ARRAY['Fintech Design', 'Loan Platform', 'Investment App', 'UX Design', 'Financial Services']),
('business-management', 'project', 'Enterprise Operations Platform | B2B UX Case Study — Barsky Design', 'Modular business management platform that reduced manual work 60% by centralizing inventory, workflows, and analytics with actionable insights across teams.', 'https://barskydesign.pro/project/business-management', 'https://barskydesign.pro/images/business-management-desktop-1.webp', ARRAY['Enterprise Software', 'B2B Platform', 'Operations Management', 'UX Design', 'Workflow Automation']),
('barskyjoint', 'project', 'Restaurant Ordering System | Food Tech UX Case Study — Barsky Design', 'End-to-end restaurant ordering experience that increased average ticket size 25% through menu clarity, guided customization, and seamless web/kiosk checkout.', 'https://barskydesign.pro/project/barskyjoint', 'https://barskydesign.pro/images/barskyjoint-desktop-1.webp', ARRAY['Restaurant Tech', 'Food Ordering', 'Kiosk Design', 'UX Design', 'POS System'])
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  canonical_url = EXCLUDED.canonical_url,
  og_image_url = EXCLUDED.og_image_url,
  keywords = EXCLUDED.keywords,
  updated_at = now();

-- Insert blog posts
INSERT INTO public.seo_meta (slug, path_type, title, description, canonical_url, og_image_url, keywords) VALUES
('finding-first-ux-job-guide', 'post', 'Finding a UX Job in 2025 | Job Search Guide for UX Designers — Barsky Design', 'Practical strategies for landing your first UX job in 2025. Portfolio tips, networking tactics, and insider advice from 15+ years in the field.', 'https://barskydesign.pro/blog/finding-first-ux-job-guide', 'https://barskydesign.pro/images/blog-finding-ux-job.jpg', ARRAY['UX Job Search', 'UX Career', 'Portfolio Tips', 'Networking', 'Design Jobs']),
('design-systems-that-get-used', 'post', 'Building Design Systems That Work | Practical Implementation Guide — Barsky Design', 'Stop building design systems that get ignored. Learn how to create systems teams actually use with practical governance, documentation, and adoption strategies.', 'https://barskydesign.pro/blog/design-systems-that-get-used', 'https://barskydesign.pro/images/blog-design-systems.jpg', ARRAY['Design Systems', 'Team Collaboration', 'Design Ops', 'Documentation', 'Component Libraries']),
('case-study-writing', 'post', 'UX Case Study Writing | Portfolio That Gets Results — Barsky Design', 'Write case studies that win clients and jobs. Structure, storytelling, and presentation tips from reviewing hundreds of UX portfolios.', 'https://barskydesign.pro/blog/case-study-writing', 'https://barskydesign.pro/images/blog-case-study-writing.jpg', ARRAY['Case Study', 'UX Portfolio', 'Design Writing', 'Portfolio Tips', 'Storytelling']),
('ai-enhanced-ux-designer-future', 'post', 'AI in UX Design | How Designers Can Leverage AI Tools — Barsky Design', 'Practical guide to using AI in UX design. From research synthesis to prototyping, learn how AI enhances (not replaces) design work.', 'https://barskydesign.pro/blog/ai-enhanced-ux-designer-future', 'https://barskydesign.pro/images/blog-ai-enhanced-ux.jpg', ARRAY['AI Design', 'UX Design', 'AI Tools', 'Design Future', 'Technology']),
('user-research-shoestring-budget', 'post', 'Low-Budget User Research | Maximum Impact Methods — Barsky Design', 'Get valuable user insights without big budgets. Guerrilla research tactics, free tools, and lean methods that actually work.', 'https://barskydesign.pro/blog/user-research-shoestring-budget', 'https://barskydesign.pro/images/blog-user-research-budget.jpg', ARRAY['User Research', 'Budget Research', 'Guerrilla Testing', 'UX Methods', 'Lean UX']),
('wireframes-to-wow-visual-hierarchy', 'post', 'Visual Hierarchy in UX Design | From Wireframes to Wow — Barsky Design', 'Master visual hierarchy to guide user attention. Practical tips for typography, spacing, and layout that improve user experience.', 'https://barskydesign.pro/blog/wireframes-to-wow-visual-hierarchy', 'https://barskydesign.pro/images/blog-visual-hierarchy.jpg', ARRAY['Visual Hierarchy', 'Typography', 'Layout Design', 'UX Design', 'Design Principles'])
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  canonical_url = EXCLUDED.canonical_url,
  og_image_url = EXCLUDED.og_image_url,
  keywords = EXCLUDED.keywords,
  updated_at = now();