/**
 * Career history — the single source of truth.
 *
 * This used to live twice, as two hand-copied arrays: one in
 * `components/about/ProfessionalJourney.tsx` and one in
 * `components/home/RecentAdventuresSection.tsx`. Both were generated by
 * gpt-engineer-app[bot] in Aug/Sep 2025, and both carried the same thirteen
 * performance percentages attributed to six named employers — "boosting
 * engagement by 40%", "reduced client costs by 10%", and so on. Nothing in
 * this repo, and no source outside it, supported any of those numbers. They
 * are the same class of fiction as the "47+ successful projects" and
 * "$150-250/hour" that the 2026-07-15 honesty pass removed from the FAQ; that
 * pass simply never reached these two files, so the claims kept being served
 * on the homepage and on /about.
 *
 * Removed 2026-08-29 by pure subtraction: every clause below is what was left
 * of the original sentence once the unverifiable quantity came out. Nothing
 * was added, reworded into a new claim, or inferred.
 *
 * The roles, employers and dates are biography and were kept as-is.
 *
 * Rule for this file, same as `testimonials.ts`: nothing goes in here that
 * cannot be traced to something real. If a number is genuinely measured and
 * Hiram can source it, it can go back — but it has to come from him.
 */
export type CareerMilestone = {
  role: string;
  company: string;
  description: string;
  duration: string;
};

export const careerHistory: CareerMilestone[] = [
  {
    role: "Senior Lead Product Designer",
    company: "PNC",
    description: "Redesigned the mobile banking interface.",
    duration: "2024 - July 2025",
  },
  {
    role: "Senior UX/UI Designer",
    company: "Bank of America",
    description: "Led UX for Loan Central and ServiceNow IRM.",
    duration: "2023 - 2024",
  },
  {
    role: "Senior User Experience Designer",
    company: "Deloitte",
    description: "User-centered prototypes and platform design work.",
    duration: "2021 - 2023",
  },
  {
    role: "UX Strategist & Design Lead",
    company: "Tata Consultancy Services",
    description: "Designed fintech apps; built a document manager app.",
    duration: "2019 - 2021",
  },
  {
    role: "Senior UX Designer",
    company: "KPMG",
    description: "Created dashboards and data visualizations.",
    duration: "2014 - 2019",
  },
  {
    role: "Senior UX Designer",
    company: "Express Scripts",
    description: "Led design initiatives across the platform.",
    duration: "2013 - 2014",
  },
];
